import logging
logging.basicConfig(level=logging.ERROR)

from dotenv import load_dotenv
load_dotenv()

from core.config.loader import ConfigLoader
from core.connection import MT5Connection
from core.data.manager import DataManager
from datetime import datetime, timezone
from backtesting import PortfolioBacktester
from strategies import create_strategy
import sys

config = ConfigLoader().global_config
conn = MT5Connection()
if not conn.connect():
    print('MT5 connection failed')
    sys.exit(1)

symbol = 'XAUUSDm'
dt_from = datetime(2025, 4, 1, tzinfo=timezone.utc)
dt_to = datetime(2025, 7, 1, tzinfo=timezone.utc)

dm = DataManager(config)
m5 = dm.prepare_data(symbol, 'M5', dt_from)
h1 = dm.prepare_data(symbol, 'H1', dt_from)
m15 = dm.prepare_data(symbol, 'M15', dt_from)
d1 = dm.prepare_data(symbol, 'D1', dt_from)

strat = create_strategy('PureBreakoutOneMinute', 'PUREBREAKOUTONEMINUTE', config)
strat.config = config
strat.min_body_ratio = 0.30
strat.sl_points = 3000
strat._warmup_done = True  # Skip warmup
print(f'M5 bars: {len(m5)}')
print(f'Strategy config: min_body_ratio={strat.min_body_ratio}, sl_points={strat.sl_points}')
strat.enabled = True
strat.min_confidence = 0.3

print(f"Starting backtest with {len(m5)} M5 bars...")
config['backtest'] = {'debug_signals': True}
config['ai_layer'] = {'enabled': False}
config['ai_layer'] = {'regime_detection': False}
bt = PortfolioBacktester(config)
from core.base_strategy import MarketData
md = MarketData(
    symbol=symbol,
    htf_candles=m5,
    m15_candles=m5,
    m5_candles=m5,
    d1_candles=d1,
    current_price=m5.close[-1],
    bid=m5.close[-1],
    ask=m5.close[-1] + 0.1,
    spread=0.1,
    point=0.0001,
    session="LONDON",
    timestamp=m5.datetime[-1] if hasattr(m5, 'datetime') else None
)
result = strat.generate_signal(md)
print(f"Manual signal test: {result}")

signals_generated = len([1 for r in strat._forensic_log if r.get('signal_generated')]) if hasattr(strat, '_forensic_log') else 0
print(f'Trades executed: {len(bt.history)}')
print(f'Signals generated by strategy: {signals_generated}')
if len(bt.history) > 10:
    print(' Sample trades:')
    for t in bt.history[:5]:
        print(f'  {t.get("direction")} Entry: {t.get("entry_price"):.2f}, PnL: {t.get("pnl"):.2f}')
for t in bt.history[:10]:
    print(f'  Direction: {t.get("direction")}, Entry: {t.get("entry_price"):.2f}, PnL: {t.get("pnl"):.2f}')